# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-05 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_place', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=400)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('notes', models.TextField()),
                ('ticket', models.BooleanField()),
                ('hashtag', models.CharField(max_length=100)),
                ('share_message', models.CharField(max_length=100)),
                ('region', models.IntegerField()),
            ],
        ),
    ]
