# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(max_length=200, upload_to=b''),
        ),
    ]
