# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='updated',
        ),
        migrations.AddField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
