# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160810_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Frame'),
        ),
    ]
