# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-06 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160805_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='admin_event', to='user.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to=b'events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, through='event.Participation', to='user.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='share_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
