# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160810_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
