# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20160806_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='event.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='user.User'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='description',
            field=models.TextField(default=b'\xe9\x80\x9a\xe5\xb8\xb8\xe5\x8f\x82\xe5\x8a\xa0\xe6\x9e\xa0'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='lower_limit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='upper_limit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='event.Event'),
        ),
    ]
