# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20160813_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='username',
        ),
    ]
