# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20160812_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='text',
        ),
    ]
