# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20160819_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('Kouchi', '高知県'), ('Shizuoka', '静岡県'), ('Okayama', '岡山県'), ('Hiroshima', '広島県'), ('Miyagi', '宮城県'), ('Kagoshima', '鹿児島県'), ('Shiga', '滋賀県'), ('Gifu', '岐阜県'), ('Yamagata', '山形県'), ('Toyama', '富山県'), ('Niigata', '新潟県'), ('Akita', '秋田県'), ('Hyogo', '兵庫県'), ('Gunnma', '群馬県'), ('Kyoto', '京都府'), ('Fukuoka', '福岡県'), ('Chiba', '千葉県'), ('Tochigi', '栃木県'), ('Fukushima', '福島県'), ('Yamanashi', '山梨県'), ('Fukui', '福井県'), ('Yamaguchi', '山口県'), ('Kagawa', '香川県'), ('Iwate', '岩手県'), ('Kumamoto', '熊本県'), ('Mie', '三重県'), ('Ehime', '愛媛県'), ('Aomori', '青森県'), ('Miyazaki', '宮崎県'), ('Saga', '佐賀県'), ('Ooita', '大分県'), ('Nagasaki', '長崎県'), ('Ibaraki', '茨城県'), ('Okinawa', '沖縄県'), ('Saitama', '埼玉県'), ('Nara', '奈良県'), ('Tokyo', '東京都'), ('Nagano', '長野県'), ('Kanagawa', '神奈川県'), ('Shimane', '島根県'), ('Hokkaido', '北海道'), ('Tottori', '鳥取県'), ('Aichi', '愛知県'), ('Osaka', '大阪府'), ('Wakayama', '和歌山県'), ('Ishikawa', '石川県'), ('Tokushima', '徳島県')], max_length=10),
        ),
    ]
