# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_auto_20160819_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='lower_limit',
        ),
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('Tottori', '鳥取県'), ('Yamaguchi', '山口県'), ('Chiba', '千葉県'), ('Shizuoka', '静岡県'), ('Nagasaki', '長崎県'), ('Okayama', '岡山県'), ('Ooita', '大分県'), ('Wakayama', '和歌山県'), ('Aomori', '青森県'), ('Niigata', '新潟県'), ('Shiga', '滋賀県'), ('Fukui', '福井県'), ('Iwate', '岩手県'), ('Okinawa', '沖縄県'), ('Miyagi', '宮城県'), ('Mie', '三重県'), ('Hyogo', '兵庫県'), ('Ishikawa', '石川県'), ('Kanagawa', '神奈川県'), ('Fukuoka', '福岡県'), ('Kumamoto', '熊本県'), ('Gifu', '岐阜県'), ('Fukushima', '福島県'), ('Ehime', '愛媛県'), ('Osaka', '大阪府'), ('Yamanashi', '山梨県'), ('Ibaraki', '茨城県'), ('Saga', '佐賀県'), ('Gunnma', '群馬県'), ('Miyazaki', '宮崎県'), ('Nagano', '長野県'), ('Yamagata', '山形県'), ('Kagawa', '香川県'), ('Hiroshima', '広島県'), ('Saitama', '埼玉県'), ('Aichi', '愛知県'), ('Akita', '秋田県'), ('Nara', '奈良県'), ('Tochigi', '栃木県'), ('Tokushima', '徳島県'), ('Tokyo', '東京都'), ('Shimane', '島根県'), ('Kagoshima', '鹿児島県'), ('Kouchi', '高知県'), ('Hokkaido', '北海道'), ('Kyoto', '京都府'), ('Toyama', '富山県')], max_length=10),
        ),
    ]
