# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20160819_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('Mie', '三重県'), ('Aomori', '青森県'), ('Osaka', '大阪府'), ('Miyagi', '宮城県'), ('Yamanashi', '山梨県'), ('Shimane', '島根県'), ('Kumamoto', '熊本県'), ('Ooita', '大分県'), ('Gunnma', '群馬県'), ('Shiga', '滋賀県'), ('Tochigi', '栃木県'), ('Saitama', '埼玉県'), ('Akita', '秋田県'), ('Ibaraki', '茨城県'), ('Tokyo', '東京都'), ('Fukushima', '福島県'), ('Hokkaido', '北海道'), ('Kyoto', '京都府'), ('Miyazaki', '宮崎県'), ('Ishikawa', '石川県'), ('Kagawa', '香川県'), ('Fukui', '福井県'), ('Wakayama', '和歌山県'), ('Iwate', '岩手県'), ('Saga', '佐賀県'), ('Toyama', '富山県'), ('Kagoshima', '鹿児島県'), ('Nara', '奈良県'), ('Fukuoka', '福岡県'), ('Kouchi', '高知県'), ('Aichi', '愛知県'), ('Ehime', '愛媛県'), ('Chiba', '千葉県'), ('Okinawa', '沖縄県'), ('Tokushima', '徳島県'), ('Hyogo', '兵庫県'), ('Nagasaki', '長崎県'), ('Shizuoka', '静岡県'), ('Gifu', '岐阜県'), ('Hiroshima', '広島県'), ('Yamaguchi', '山口県'), ('Okayama', '岡山県'), ('Niigata', '新潟県'), ('Kanagawa', '神奈川県'), ('Nagano', '長野県'), ('Yamagata', '山形県'), ('Tottori', '鳥取県')], max_length=10),
        ),
    ]
