# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_auto_20160819_1109'),
        ('event', '0028_auto_20160819_1009'),
    ]

    operations = [
    ]
