# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_auto_20160819_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private_notes',
            field=models.TextField(blank=True),
        ),
    ]
