# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_event_private_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
    ]
