# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_remove_event_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='upper_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
