# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0035_auto_20160822_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participating_frame', through='event.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
