# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_auto_20170817_0615'),
        ('event', '0037_auto_20170818_0323'),
    ]

    operations = [
    ]
