# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_merge_20170819_0344'),
        ('event', '0042_auto_20170819_0238'),
    ]

    operations = [
    ]
