# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_merge_20170819_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=35.7291),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=139.7191),
        ),
    ]
