# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_merge_20170819_0454'),
        ('event', '0038_merge_20170818_0831'),
    ]

    operations = [
    ]
