# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_auto_20170819_0348'),
        ('event', '0044_auto_20170822_0819'),
    ]

    operations = [
    ]
