# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_merge_20170822_1304'),
        ('event', '0045_merge_20170823_0118'),
    ]

    operations = [
    ]
