# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_auto_20170823_0220'),
        ('event', '0046_auto_20170823_0747'),
    ]

    operations = [
    ]
