# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('emergency_contact', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('region', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='users/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('follow_tag', models.ManyToManyField(null=True, related_name='follower', to='tag.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
