# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-05 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('telephone', models.CharField(max_length=11)),
                ('emergency_contact', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('region', models.IntegerField()),
                ('fb_access_token', models.CharField(max_length=100)),
                ('twitter_access_token', models.CharField(max_length=100)),
            ],
        ),
    ]
