# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-05 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_tag',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
