# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160810_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow_tag',
            field=models.ManyToManyField(blank=True, related_name='follower', to='tag.Tag'),
        ),
    ]
