# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160812_0847'),
        ('user', '0005_user_sex'),
    ]

    operations = [
    ]
