# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160812_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
