# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userreviewlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_todo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
