# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_userreviewlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviewlist',
            old_name='rate_user',
            new_name='rated_user',
        ),
    ]
