# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20160819_0830'),
        ('user', '0017_user_user_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(null=True)),
                ('description', models.TextField(default='ボランティアできること')),
                ('user_todo', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow_tag',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frame',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
    ]
