# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_userreviewlist2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviewlist2',
            name='from_rete_user',
        ),
        migrations.RemoveField(
            model_name='userreviewlist2',
            name='to_rate_user',
        ),
        migrations.RemoveField(
            model_name='userreviewlist',
            name='rated_user',
        ),
        migrations.AddField(
            model_name='userreviewlist',
            name='from_rete_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_rete_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreviewlist',
            name='to_rate_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_rate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserReviewList2',
        ),
    ]
