# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20170817_0717'),
        ('user', '0020_auto_20170817_0835'),
    ]

    operations = [
    ]
