# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20160819_0830'),
        ('user', '0021_merge_20170817_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_tag',
            field=models.ManyToManyField(blank=True, related_name='follower', to='tag.Tag'),
        ),
    ]
