# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20170818_0821'),
        ('user', '0022_user_follow_tag'),
    ]

    operations = [
    ]
