# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userreviewlist_post_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewlist',
            name='post_day',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 7, 41, 22, 620609), editable=False, null=True),
        ),
    ]
