# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_merge_20170818_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frame',
            new_name='Skill',
        ),
    ]
