# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20170819_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_todo',
        ),
    ]
