# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20170818_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewlist',
            name='post_day',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 7, 45, 44, 486992), editable=False, null=True),
        ),
    ]
