# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_user_user_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user_todo',
            new_name='skilltodo',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='frame_user',
            new_name='userskill',
        ),
    ]
