# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20170818_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewlist',
            name='finish_or_not',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreviewlist',
            name='host_or_participate',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='userreviewlist',
            name='post_day',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
