# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170818_1829'),
        ('user', '0030_auto_20170818_0748'),
        ('user', '0021_auto_20170818_0251'),
    ]

    operations = [
    ]
