# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20170818_0748'),
        ('user', '0021_merge_20170817_1000'),
    ]

    operations = [
    ]
