# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_merge_20170819_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewlist',
            name='post_day',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
