# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20170818_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreviewlist',
            name='finish_or_not',
        ),
        migrations.RemoveField(
            model_name='userreviewlist',
            name='host_or_participate',
        ),
    ]
