# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20170818_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviewlist',
            name='event_host',
            field=models.NullBooleanField(default=False),
        ),
    ]
