# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20170819_0459'),
        ('user', '0027_auto_20170822_0913'),
    ]

    operations = [
    ]
