# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20170818_0943'),
        ('user', '0032_auto_20170819_0459'),
    ]

    operations = [
    ]
