# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_userreviewlist_event_host'),
        ('user', '0032_auto_20170819_0459'),
    ]

    operations = [
    ]
