# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_merge_20170823_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewlist',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
