# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_merge_20170822_0917'),
        ('user', '0034_merge_20170823_0118'),
    ]

    operations = [
    ]
