# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_merge_20170823_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='userskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
