# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20170823_0246'),
        ('user', '0035_auto_20170823_0141'),
    ]

    operations = [
    ]
