# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_merge_20170823_0202'),
        ('user', '0038_merge_20170823_0715'),
    ]

    operations = [
    ]
