# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_merge_20170823_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreviewlist',
            old_name='event_host',
            new_name='from_event_host',
        ),
    ]
