# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_merge_20170823_0807'),
        ('user', '0039_auto_20170825_0551'),
    ]

    operations = [
    ]
