# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20170825_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('ja-jp', '日本語')], default='ja-jp', max_length=10, null=True, verbose_name='Language'),
        ),
    ]
