# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20170825_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
