# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20170826_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='userskill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviewlist',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (5, '5'), (3, '3'), (4, '4'), (2, '2')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
