# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_merge_20170825_0600'),
        ('user', '0048_auto_20170826_0222'),
    ]

    operations = [
    ]
