# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20170826_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreviewlist',
            name='rating',
            field=models.IntegerField(choices=[(4, '4'), (2, '2'), (1, '1'), (5, '5'), (3, '3')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
