# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20170826_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewlist',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
