# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_auto_20170826_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='user.UserComment'),
        ),
        migrations.AlterField(
            model_name='userreviewlist',
            name='rating',
            field=models.IntegerField(choices=[(4, '4'), (3, '3'), (5, '5'), (2, '2'), (1, '1')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
