# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 02:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_auto_20170826_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='userreviewlist',
            name='rating',
            field=models.IntegerField(choices=[(5, '5'), (2, '2'), (4, '4'), (3, '3'), (1, '1')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
