# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20170826_0316'),
        ('user', '0057_auto_20170826_1917'),
    ]

    operations = [
    ]
