# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-06 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to=b'group/'),
        ),
    ]
