# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20160810_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='OHMYGOD'),
            preserve_default=False,
        ),
    ]
