# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20160806_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='event',
            field=models.ManyToManyField(blank=True, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'group/'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(default=b'Normal', max_length=20),
        ),
    ]
