# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20160812_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
    ]
