# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_remove_group_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, through='group.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
